version: '3.9'

services:
  evo-test-app:
    build: ./
    command: ./main
    ports:
      - 8080:8080
    depends_on:
      - postgres
    environment:
      - POSTGRES_USER=evo
      - DB_HOST=postgres
      - POSTGRES_PASSWORD=evo

  postgres:
    restart: always
    image: postgres:latest
    volumes:
      - ./.database/postgres/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=evo
      - POSTGRES_PASSWORD=evo
    ports:
      - 5432:5432
